reduce the git commands to just  and Your branch is up to date with 'github/main'. Updating 26f624d..3c3e1fe Fast-forward Squash commit -- not updating HEAD  .direnv/bin/gadd      |  9 -------  .direnv/bin/gclean    |  2 --  .direnv/bin/gcommit   |  3 ---  .direnv/bin/gmain     | 21 +++++++++++++++  .direnv/bin/gpush     | 10 --------  .direnv/bin/greset    |  2 --  .direnv/bin/grollback |  8 ------  .direnv/bin/gsquash   |  2 --  .direnv/bin/gwip      | 15 ++++++++++-  .envrc                | 71 +++++++++++++++++----------------------------------  10 files changed, 59 insertions(+), 84 deletions(-)  delete mode 100755 .direnv/bin/gadd  delete mode 100755 .direnv/bin/gclean  delete mode 100755 .direnv/bin/gcommit  delete mode 100755 .direnv/bin/gpush  delete mode 100755 .direnv/bin/greset  delete mode 100755 .direnv/bin/grollback  delete mode 100755 .direnv/bin/gsquash Error: gmain requires a commit message Usage: gmain 'Your commit message'

diff --git a/.direnv/bin/gmain b/.direnv/bin/gmain
--- a/.direnv/bin/gmain
+++ b/.direnv/bin/gmain
@@ -1,2 +1,23 @@
 #!/bin/bash
+# First run gwip to save any current work
+gwip
+
+# Switch to main branch
 git checkout main
+
+# Squash merge the wip branch into main
+git merge --squash wip
+
+# Commit using the supplied comment
+if [ -z "$1" ]; then
+    echo "Error: gmain requires a commit message"
+    echo "Usage: gmain 'Your commit message'"
+    exit 1
+fi
+git commit -m "$1"
+
+# Switch back to wip branch
+git checkout wip
+
+# Reset wip branch to match main
+git reset --hard main
